use [].forEach on NodeList instance
querySelectorAll returns a NodeList which doesn't have a `forEach` method but `[].forEach` works fine with NodeLists. 

Before thins change, I see
> eError: el.forEach is not a function 

https://css-tricks.com/snippets/javascript/loop-queryselectorall-matches/